* 研究室での統一的な枠組みを作る

* 目標

- 研究ミーティングで、過去に誰かが先生に指摘された内容と同じ内容の指摘
  をされないようにする。

プリンシプル3に沿った目標になっている。

(プリンシプル)
1. 情報通信技術の最先端に位置し、開拓者になる
2. 研究室のメンバがわれわれの強さの源である
3. 先人に学び、不断の改善でそれを超える


** 例

*** 例1
研究ミーティングにおいて

Q. サーバーって何ですか？

上記のような質問は無駄な質問である。なぜなら、わざわざ先生に頼らなくて
も調べれば自分1人で答えを出せる質問だからである。

emacsの使い方が分からなくて...
redmineの使い方が分からなくて...
という質問も同じである。


*** 例2
研究ミーティングにおいて

「(他の選択肢は検討していませんが) 案 A が良いと思ってます」

上記のような主張は自分の直感に頼っており、"研究ミーティングにおけ
るアンチパターン"の原則に反している。

(研究ミーティングにおけるアンチパターン)
原則: 論理的に考える
原則: 研究の主役はあなたである
原則: 直感に頼らない
原則: 楽をしようとしない

これと全く同じ指摘がredmineのヒント、コツに書かれている。この指摘が過
去にされた事を事前に知っていると回避できるはずである。


*** 例3
研究ミーティングにおいて自分の番が回ってきたとき、

「お疲れ様です。shunです。今から画面共有をします。画面の方は見えていま
すでしょうか？？」

普通に考えると何もおかしくないが、大崎研では

「画面共有をします。」

と伝えるだけで十分であり、それ以上は無駄な説明であると解釈されてしまう
現象がある。


** どうしたら解決できるか？

*** 例1 の解決策
自分だけで調べて解決できる質問であるか、
同期に聞けば解決できる質問であるか、
先輩に聞けば解決できる質問であるか、
先生に聞かないと解決できない質問であるか、
の線引きをしっかりとできるようにする。

プリンシプルの2より、基本的にはすぐに同期、先輩を頼る形が望ましい。

また、基本的に理解度が同じレベルの者同士で解決した方がリソース効率が良
いので、

自分で調べる → 同期に聞く → 先輩に聞く → 先生に聞く

という順序で質問をしていくと良いだろう。

ここで、自分で調べる → 同期に聞く の過程で、できるだけ解決できるように
するために


*** 例2 の解決策

redmineのヒント、コツを全て確認し、我々上級生の経験から特に重要だと思
われる(先生が何度もしてきそうな指摘)内容のものをピックアップし、それを
チェックリスト形式でまとめる。研究ミーティングの前にセルフチェック(ク
ロスチェック？)をするようにする。


*** 例3 の解決策

研究ミーティング前に講習を行なう。
講習では以下のような内容を説明する。

- 研究ミーティングのルールや目的
- 資料の作り方やそれに関するルール
- 校閲依頼の文章の書き方
- 理想的な発表の仕方の実演(prep法 で説明する等。)



* 我々がやるべきこと

- "自分で調べる → 同期に聞く → 先輩に聞く → 先生に聞く" のような、それ
  に沿って行動すれば間違いなくプリンシプルに沿った行動ができるサブプリ
  ンシプル的なもの(行動指針?エスカレーション？)を考える。
→この流れで良いと思うが、どのように全体に周知させるのかを考える必要ア
リ。(kazuma-a)

→ 講習で説明する or 紙にまとめてくばる


- 過去に投稿されたヒント、コツの記事と先生が書いている tips 全てを読み、
  重要なものをチェックリスト形式でまとめる。
→全部伝えるというよりも、AIなどの進歩により不要なものも結構あると思う
ので、厳選して伝えると良いと思う(kazuma-a)。

- 研究ミーティングのルールや目的、資料の作り方やそれに関するルールを1
  つの場所にまとめる。理想的な発表を実演できるようになる。

→LLM or API を使って、ミーティング資料や質問事項を入れたらどのように改
善すべきかを出力してくれるサービスを作るのが良いかも(kazuma-a)。

→ LLMを使うにしても、先生に質問するべき内容か、そうでないか言語化でき
る必要がる。
